### ISSUE TITLE
[V2] Unable to set azure-iot-edge network as "host" network for BLE Compatibility

### ISSUE THREAD

**Issue by damaggio** [Azure/iot-edge-v1#517]
In an IoT Edge project on a RPi3 a container module needs to access a bluetooth device inside the IoT device. 
In order to do that, outside the IoT Edge Environment you have to set the --net as host.
When you deploy the module using IoT Edge, even if defining the host network using the docker API, it doesn´t work because IoT Edge uses their own docker network (azure-iot-edge, type: bridge). 
The Docker Container Creation Option is:​

{
  "HostConfig": {
    "NetworkMode": "host"
  }
}

The error received is:
"Error response from daemon: failed to add interface vetha6faad3 to sandbox: error setting interface "vetha6faad3" IP to 172.18.0.5/16: cannot program address 172.18.0.5/16 in sandbox interface because it conflicts with existing route"
​
In theory we should need be able to deploy a module to docker network host or modify the docker network azure-iot-edge to the type host

**Comment by Zuendelmeister** [comment]
I also wonder about that. Any ideas?

**Comment by dariuszparys** [comment]
There is some more background on the root of this issue here:

https://github.com/moby/moby/issues/16208
https://patchwork.kernel.org/patch/9898285/

Currently Edge is creating a bridged network and all modules will be instantiated in this network. Maybe there should be a way to break this up or provide some guidance / thoughts on how this scenario would be possible in the near future? Tagging some people @damonbarry @darobs @varunpuranik

**Comment by xtellurian** [comment]
Also experiencing this issue.

Pretty big problem, IMO, since Bluetooth is a core IoT technology

**Comment by kyberpunk** [comment]
Any updates? Is there any workaround to access host network interfaces?

**Comment by helgemahrt** [comment]
Facing the same issue here.

**Comment by helgemahrt** [comment]
I found a manual workaround that seems to work for me: Once the edgeAgent has created the edge module, I manually switch it over to the host network with:
docker network disconnect azure-iot-edge <module>
docker network connect host <module>

**Comment by danigian** [comment]
@helgemahrt What if the module restarts?

**Comment by damaggio** [comment]
@helgemahrt What if the module restarts?

**Comment by helgemahrt** [comment]
It only works until the next docker pull is executed. AFAIK that only happens when you change the container tag in the deployment or when the runtime restarts. If the module fails the runtime will try to start it, but will not pull it again.

**Comment by matsujirushi** [comment]
I had error message.
Could you tell me any idea?

```
pi@raspberrypi:~ $ docker network disconnect azure-iot-edge tempSensor
pi@raspberrypi:~ $ docker network list
NETWORK ID          NAME                DRIVER              SCOPE
7876c31a2b83        azure-iot-edge      bridge              local
7522a5fd5f2d        bridge              bridge              local
bcd6f880b86f        host                host                local
fd37c4b0479f        none                null                local
pi@raspberrypi:~ $ docker network connect host tempSensor
Error response from daemon: container cannot be disconnected from host network or connected to host network
pi@raspberrypi:~ $
```

**Comment by hogewachtel** [comment]
Facing the same problem here. Any update on a solution?

**Comment by avranju** [comment]
The fix for this issue is under review right now. This will work when Azure IoT Edge becomes generally available. You'll be able to specify the network configuration via "create options" in the deployment and Edge Agent will honor that setting and not try to add the container to the bridged network. The flip side of this change is that the container loses the ability to access other modules in the deployment directly by name, i.e., module names no longer resolve to their container IP addresses since the container which is on the host network is not part of the bridged network. Modules that wish to be accessible from the host network can achieve that by port mapping the container port to a host port.

**Comment by avranju** [comment]
This issue has been addressed in the [GA release](https://github.com/azure/iotedge). Do please let me know if this does not work out. Closing issue.

**Comment by myagley** [comment]
Just for completeness, the following module `createOptions` should get you going:

```json
"createOptions": {
  "NetworkingConfig": {
    "EndpointsConfig": {
      "host": {}
    }
  },
  "HostConfig": {
    "NetworkMode": "host"
  }
}
```

**Comment by Jazmine9** [comment]
@myagley Thanks, This worked perfectly for me.

**Comment by keshava-hm** [comment]
What's the 

> Just for completeness, the following module `createOptions` should get you going:
> 
> ```json
> "createOptions": {
>   "NetworkingConfig": {
>     "EndpointsConfig": {
>       "host": {}
>     }
>   },
>   "HostConfig": {
>     "NetworkMode": "host"
>   }
> }
> ```

Will this work on Windows OS with Windows containers?

**Comment by iconics-pavel** [comment]
> 
> 
> What's the
> 
> > Just for completeness, the following module `createOptions` should get you going:
> > ```json
> > "createOptions": {
> >   "NetworkingConfig": {
> >     "EndpointsConfig": {
> >       "host": {}
> >     }
> >   },
> >   "HostConfig": {
> >     "NetworkMode": "host"
> >   }
> > }
> > ```
> 
> Will this work on Windows OS with Windows containers?

Network mode 'host' with 'host' EndpointConfig is still not working in Azure IoT Edge running on Windows OS. Container with such startup options is not started. Are there any news in this issue?

**Comment by arsing** [comment]
Windows does not support `host` networking, as documented by Docker at https://docs.docker.com/network/host/ So it's expected that it won't work, and is not related to IoT Edge.

Now, as documented at https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies , you could create a new Docker network yourself using the `transparent` driver. If you then set that network name to be the value of `moby_runtime.network` in `config.yaml`, all your modules would be started on this network instead of the default `nat` network.

However, Moby on Windows has another bug where any non-built-in networks become unusable after a reboot. This is because they get a new ID but all containers remain associated with the old ID, so they don't start. The only mitigation is to delete all containers and let them be recreated, so that they attach to the new ID. This bug is also why IoT Edge itself does not default to using the `azure-iot-edge` network on Windows like on Linux, and instead uses the built-in `nat` network. I suspect that any network you create manually would have the same problem.

If the network you create *does* have that problem, then you will need to follow up with https://github.com/moby/moby/issues

**Comment by payalgaikwad42** [comment]
Hi, I am facing the same issue with deployment of modules on iotedge. 
IoT Edge version: 1.0.8
operating system: linux-ubuntu 18.04
Architecture: arm64v8

I have 5 custom modules deployed on azure iotedge one of them is mongodb container. My other modules Deepstream, BoundaryTracker and EdgeAggregator are connecting to mongodb. 
I am facing issue with connecting to mongo database. It says connection refused. 
I have mentioned "network mode host"  in my container create option for mongodb container as follows: 

`"createOptions": {
  "NetworkingConfig": {
    "EndpointsConfig": {
      "host": {}
    }
  },
  "HostConfig": {
    "NetworkMode": "host"
  }
}`

I have also done the port mapping. tcp/27017:27017

But after deployment i am facing following issue:
`(Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module MongoDB: Could not start module MongoDB
caused by: Could not start module MongoDB
caused by: failed to add interface vetha0a2d13 to sandbox: error setting interface "vetha0a2d13" IP to 172.18.0.3/16: cannot program address 172.18.0.3/16 in sandbox interface because it conflicts with existing route {Ifindex: 7 Dst: 172.18.0.0/16 Src: 172.18.0.1 Gw: <nil> Flags: [] Table: 254}, StatusCode:500, at: at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 194`

I have tried the option of running mongodb image locally using docker run with option network=host and connect to it from host it works that way. But mentioning networkmode in IoT Edge environment gives above issue, 

I have looked into the solutions given the issue but they are not working for me. Are there any other solutions I can look into.

**Comment by iconics-pavel** [comment]
> 
> 
> Windows does not support `host` networking, as documented by Docker at https://docs.docker.com/network/host/ So it's expected that it won't work, and is not related to IoT Edge.
> 
> Now, as documented at https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies , you could create a new Docker network yourself using the `transparent` driver. If you then set that network name to be the value of `moby_runtime.network` in `config.yaml`, all your modules would be started on this network instead of the default `nat` network.
> 
> However, Moby on Windows has another bug where any non-built-in networks become unusable after a reboot. This is because they get a new ID but all containers remain associated with the old ID, so they don't start. The only mitigation is to delete all containers and let them be recreated, so that they attach to the new ID. This bug is also why IoT Edge itself does not default to using the `azure-iot-edge` network on Windows like on Linux, and instead uses the built-in `nat` network. I suspect that any network you create manually would have the same problem.
> 
> If the network you create _does_ have that problem, then you will need to follow up with https://github.com/moby/moby/issues

Thanks for advise with 'transparent' network. But I am not able to start IoT Edge on Windows when transparent network is set in iotedge/confix.yaml file. The edgeHub module is not correctly initialized - see https://github.com/Azure/iotedge/issues/2822

**Comment by amit12cool** [comment]
Applying above solution works for me I.e. I'm able to access my custom module running nodejs server through localhost.
But the leaf device is not connecting to edge in transparent gateway design. I'm using x509 to connect leaf to edge.Any idea of issue?
